#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/browserslist@4.28.2/node_modules/browserslist/node_modules:/tmp/dishday-vstore/browserslist@4.28.2/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/browserslist@4.28.2/node_modules/browserslist/node_modules:/tmp/dishday-vstore/browserslist@4.28.2/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../../../../tmp/dishday-vstore/browserslist@4.28.2/node_modules/browserslist/cli.js" "$@"
else
  exec node  "$basedir/../../../../../../../../../tmp/dishday-vstore/browserslist@4.28.2/node_modules/browserslist/cli.js" "$@"
fi
