#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/react-native@0.76.5_@babel+core@7_biawgk4lgc2a6eoy7prt34rnhy/node_modules/react-native/node_modules:/tmp/dishday-vstore/react-native@0.76.5_@babel+core@7_biawgk4lgc2a6eoy7prt34rnhy/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/react-native@0.76.5_@babel+core@7_biawgk4lgc2a6eoy7prt34rnhy/node_modules/react-native/node_modules:/tmp/dishday-vstore/react-native@0.76.5_@babel+core@7_biawgk4lgc2a6eoy7prt34rnhy/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../react-native/cli.js" "$@"
else
  exec node  "$basedir/../react-native/cli.js" "$@"
fi
