#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/tailwindcss@3.4.19_tsx@4.22.3/node_modules/tailwindcss/lib/node_modules:/tmp/dishday-vstore/tailwindcss@3.4.19_tsx@4.22.3/node_modules/tailwindcss/node_modules:/tmp/dishday-vstore/tailwindcss@3.4.19_tsx@4.22.3/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/tailwindcss@3.4.19_tsx@4.22.3/node_modules/tailwindcss/lib/node_modules:/tmp/dishday-vstore/tailwindcss@3.4.19_tsx@4.22.3/node_modules/tailwindcss/node_modules:/tmp/dishday-vstore/tailwindcss@3.4.19_tsx@4.22.3/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../tailwindcss/lib/cli.js" "$@"
else
  exec node  "$basedir/../tailwindcss/lib/cli.js" "$@"
fi
