#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/jiti@2.7.0/node_modules/jiti/lib/node_modules:/tmp/dishday-vstore/jiti@2.7.0/node_modules/jiti/node_modules:/tmp/dishday-vstore/jiti@2.7.0/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/jiti@2.7.0/node_modules/jiti/lib/node_modules:/tmp/dishday-vstore/jiti@2.7.0/node_modules/jiti/node_modules:/tmp/dishday-vstore/jiti@2.7.0/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../../tmp/dishday-vstore/jiti@2.7.0/node_modules/jiti/lib/jiti-cli.mjs" "$@"
else
  exec node  "$basedir/../../../../../../../tmp/dishday-vstore/jiti@2.7.0/node_modules/jiti/lib/jiti-cli.mjs" "$@"
fi
