#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/prettier@3.8.3/node_modules/prettier/bin/node_modules:/tmp/dishday-vstore/prettier@3.8.3/node_modules/prettier/node_modules:/tmp/dishday-vstore/prettier@3.8.3/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/prettier@3.8.3/node_modules/prettier/bin/node_modules:/tmp/dishday-vstore/prettier@3.8.3/node_modules/prettier/node_modules:/tmp/dishday-vstore/prettier@3.8.3/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../prettier/bin/prettier.cjs" "$@"
else
  exec node  "$basedir/../prettier/bin/prettier.cjs" "$@"
fi
