#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/pino@9.14.0/node_modules/pino/node_modules:/tmp/dishday-vstore/pino@9.14.0/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/pino@9.14.0/node_modules/pino/node_modules:/tmp/dishday-vstore/pino@9.14.0/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../pino/bin.js" "$@"
else
  exec node  "$basedir/../pino/bin.js" "$@"
fi
