#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/prisma@6.19.3_typescript@5.9.3/node_modules/prisma/build/node_modules:/tmp/dishday-vstore/prisma@6.19.3_typescript@5.9.3/node_modules/prisma/node_modules:/tmp/dishday-vstore/prisma@6.19.3_typescript@5.9.3/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/prisma@6.19.3_typescript@5.9.3/node_modules/prisma/build/node_modules:/tmp/dishday-vstore/prisma@6.19.3_typescript@5.9.3/node_modules/prisma/node_modules:/tmp/dishday-vstore/prisma@6.19.3_typescript@5.9.3/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../prisma/build/index.js" "$@"
else
  exec node  "$basedir/../prisma/build/index.js" "$@"
fi
