#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/terser@5.47.1/node_modules/terser/bin/node_modules:/tmp/dishday-vstore/terser@5.47.1/node_modules/terser/node_modules:/tmp/dishday-vstore/terser@5.47.1/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/terser@5.47.1/node_modules/terser/bin/node_modules:/tmp/dishday-vstore/terser@5.47.1/node_modules/terser/node_modules:/tmp/dishday-vstore/terser@5.47.1/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../../../../tmp/dishday-vstore/terser@5.47.1/node_modules/terser/bin/terser" "$@"
else
  exec node  "$basedir/../../../../../../../../../tmp/dishday-vstore/terser@5.47.1/node_modules/terser/bin/terser" "$@"
fi
