#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/typescript@5.9.3/node_modules/typescript/bin/node_modules:/tmp/dishday-vstore/typescript@5.9.3/node_modules/typescript/node_modules:/tmp/dishday-vstore/typescript@5.9.3/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/typescript@5.9.3/node_modules/typescript/bin/node_modules:/tmp/dishday-vstore/typescript@5.9.3/node_modules/typescript/node_modules:/tmp/dishday-vstore/typescript@5.9.3/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../typescript/bin/tsc" "$@"
else
  exec node  "$basedir/../typescript/bin/tsc" "$@"
fi
