#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/tsx@4.22.3/node_modules/tsx/dist/node_modules:/tmp/dishday-vstore/tsx@4.22.3/node_modules/tsx/node_modules:/tmp/dishday-vstore/tsx@4.22.3/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/tsx@4.22.3/node_modules/tsx/dist/node_modules:/tmp/dishday-vstore/tsx@4.22.3/node_modules/tsx/node_modules:/tmp/dishday-vstore/tsx@4.22.3/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../tsx/dist/cli.mjs" "$@"
else
  exec node  "$basedir/../tsx/dist/cli.mjs" "$@"
fi
