#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/vitest@2.1.9_@types+node@22.19.19_kmhgahgoqcpa333tgvwvmdd7oe/node_modules/vitest/node_modules:/tmp/dishday-vstore/vitest@2.1.9_@types+node@22.19.19_kmhgahgoqcpa333tgvwvmdd7oe/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/vitest@2.1.9_@types+node@22.19.19_kmhgahgoqcpa333tgvwvmdd7oe/node_modules/vitest/node_modules:/tmp/dishday-vstore/vitest@2.1.9_@types+node@22.19.19_kmhgahgoqcpa333tgvwvmdd7oe/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../vitest/vitest.mjs" "$@"
else
  exec node  "$basedir/../vitest/vitest.mjs" "$@"
fi
