#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/tmp/dishday-vstore/vite@5.4.21_@types+node@22.19.19__bdgwnm4usdog3kicmvd3n3dfrq/node_modules/vite/bin/node_modules:/tmp/dishday-vstore/vite@5.4.21_@types+node@22.19.19__bdgwnm4usdog3kicmvd3n3dfrq/node_modules/vite/node_modules:/tmp/dishday-vstore/vite@5.4.21_@types+node@22.19.19__bdgwnm4usdog3kicmvd3n3dfrq/node_modules:/tmp/dishday-vstore/node_modules"
else
  export NODE_PATH="/tmp/dishday-vstore/vite@5.4.21_@types+node@22.19.19__bdgwnm4usdog3kicmvd3n3dfrq/node_modules/vite/bin/node_modules:/tmp/dishday-vstore/vite@5.4.21_@types+node@22.19.19__bdgwnm4usdog3kicmvd3n3dfrq/node_modules/vite/node_modules:/tmp/dishday-vstore/vite@5.4.21_@types+node@22.19.19__bdgwnm4usdog3kicmvd3n3dfrq/node_modules:/tmp/dishday-vstore/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../../../../tmp/dishday-vstore/vite@5.4.21_@types+node@22.19.19__bdgwnm4usdog3kicmvd3n3dfrq/node_modules/vite/bin/vite.js" "$@"
else
  exec node  "$basedir/../../../../../../../../../tmp/dishday-vstore/vite@5.4.21_@types+node@22.19.19__bdgwnm4usdog3kicmvd3n3dfrq/node_modules/vite/bin/vite.js" "$@"
fi
