/**
 * Bull worker that consumes ai-jobs and persists results.
 * Run as a separate process in prod: `node dist/queue/ai-worker.js`.
 * In dev it's started in-process by app.ts when REDIS_URL is set.
 */

import { logger } from '../config/logger.js';
import { createContainer } from '../container.js';
import { generateWeeklyPlan } from '../services/ai/meal-plan-generator.js';
import { aiQueue, type AiJobResult } from './ai-queue.js';

export function startAiWorker() {
  const container = createContainer();

  aiQueue.process('meal_plan', async (job): Promise<AiJobResult> => {
    const { userId, input } = job.data;
    const weekStart = (input.weekStart as string) ?? new Date().toISOString().slice(0, 10);

    logger.info({ jobId: job.id, userId, weekStart }, 'AI meal-plan job started');

    // Load profile AND user — profile drives dietary rules, user.locale drives
    // the language the AI should write recipe titles / descriptions in.
    const [profile, user] = await Promise.all([
      container.repos.users.getProfile(userId),
      container.repos.users.findById(userId),
    ]);
    const result = await generateWeeklyPlan(container.repos, {
      userId,
      profile,
      weekStart,
      locale: user?.locale ?? null,
    });

    // Persist as MealPlan + entries. Recipes generated by AI are saved as
    // source='ai' so they can be referenced from meal_plan_entries.
    const plan = await container.repos.mealPlans.create({
      userId,
      weekStart,
      generatedBy: 'ai',
      aiPromptSummary: result.promptSummary,
    });

    for (const day of result.plan.days) {
      for (const meal of day.meals) {
        const recipe = await container.repos.recipes.create({
          title: meal.title,
          slug: `ai-${plan.id}-${day.dayOfWeek}-${meal.mealType}-${Date.now()}`,
          description: meal.description,
          authorId: userId,
          source: 'ai',
          servings: 1,
          caloriesPerServing: meal.calories,
          proteinG: meal.proteinG,
          carbsG: meal.carbsG,
          fatG: meal.fatG,
          // Fall back to sensible defaults when the model doesn't supply these.
          prepTimeMin: meal.prepTimeMin ?? defaultPrepTime(meal.mealType),
          cookTimeMin: meal.cookTimeMin ?? defaultCookTime(meal.mealType),
          tags:
            meal.tags && meal.tags.length > 0 ? meal.tags : defaultTags(meal.mealType),
          cuisine: meal.cuisine ?? null,
          isPublic: false,
          isApproved: true,
          mealType: [meal.mealType],
          ingredients: meal.ingredients.map((ing, i) => ({
            name: ing.name,
            quantity: ing.quantity,
            unit: ing.unit,
            notes: null,
            orderIndex: i,
          })),
        });
        await container.repos.mealPlans.addEntry(plan.id, {
          recipeId: recipe.id,
          dayOfWeek: day.dayOfWeek as 0 | 1 | 2 | 3 | 4 | 5 | 6,
          mealType: meal.mealType,
          servings: 1,
        });
      }
    }

    logger.info({ jobId: job.id, planId: plan.id }, 'AI meal-plan job completed');
    return { ok: true, resultId: plan.id };
  });

  aiQueue.on('failed', (job, err) =>
    logger.error({ jobId: job.id, err: err.message }, 'AI job failed'),
  );

  return aiQueue;
}

// Defaults used when the AI provider doesn't include these fields in its output.
function defaultPrepTime(mealType: string): number {
  switch (mealType) {
    case 'breakfast':
      return 5;
    case 'snack':
      return 3;
    case 'lunch':
      return 10;
    case 'dinner':
      return 15;
    default:
      return 10;
  }
}

function defaultCookTime(mealType: string): number {
  switch (mealType) {
    case 'breakfast':
      return 7;
    case 'snack':
      return 0;
    case 'lunch':
      return 15;
    case 'dinner':
      return 25;
    default:
      return 15;
  }
}

function defaultTags(mealType: string): string[] {
  switch (mealType) {
    case 'breakfast':
      return ['quick', 'easy'];
    case 'snack':
      return ['quick', 'no-cook'];
    case 'lunch':
      return ['easy'];
    case 'dinner':
      return ['comfort'];
    default:
      return ['easy'];
  }
}
